### ISSUE TITLE
[Improvement] Filter or search on the index page

### ISSUE THREAD

**Issue by geronime** [Sesu8642/InfusionTimer#14]
Low priority improvement: It would be great to have some quick search input field on top of the tea index page to filter/search for teas. As the list is getting longer and the teas used the most recently stay on top, it gets more time consuming to find the tea configuration I'm looking for.

**Comment by Sesu8642** [comment]
Will be in the next (pre-)release. Please let me know if the UI is intuitive and works as expected.

**Comment by geronime** [comment]
Tested in the pre-release together with #12, works well. Closing.

**Comment by geronime** [comment]
Just noticed that the search function is in the production release that my phone auto-upgraded to. I immediately used it to effortlessly find the tea profile I was looking for. Really handy, thanks for implementing!

**Comment by Sesu8642** [comment]
I'm glad you like it! :)
