### ISSUE TITLE
[Improvement] Button to clear tea session state

### ISSUE THREAD

**Issue by geronime** [Sesu8642/InfusionTimer#17]
Small UX improvement as a follow-up to #5 - noticeable only with Gong Fu style sessions with double digit infusions: When I don't finish a tea session and I know the next time I'm going to start over, it takes many clicks to go back to the first infusion to clear the session state. It would be helpful to have a "reset" button (confirmable by a dialog) on the tea detail page to reset the session in progress.

**Comment by Sesu8642** [comment]
Long pressing the infusion back button will now reset the session. Not sure if a confirmation dialog is needed. Lets see if accidental resets will happen.

**Comment by geronime** [comment]
I see this is not yet part of v1.4.0, right? When will you release this feature?

**Comment by Sesu8642** [comment]
Exactly. I'll try to release in the coming weeks. :)

**Comment by geronime** [comment]
By chance I picked up a long-steeping tea, Hou Kui, for which I use the timer. Therefore I noticed the UI facelift coming from yesterday's release. I can happily confirm this feature works. Thank you!

**Comment by Sesu8642** [comment]
Great to hear. Thanks for your feedback! :)
