### ISSUE TITLE
[Improvement] (configurable) alarm on timer end

### ISSUE THREAD

**Issue by geronime** [Sesu8642/InfusionTimer#3]
Currently I don't get any acoustic feedback that the infusion is brewed. Brewing tea while working, in particular with some late session (longer) infusions I tend to shift focus from the tea brewing back to work and then to forget about the tea in the pot. Some (configurable) beep/alarm once the timer is finished would help with this.

**Comment by Sesu8642** [comment]
Thank you for your suggestions :)
This one is actually implemented already. There should be a ring sound when the timer finishes. It uses the media volume which you might have set to 0. Could you please re-test this making sure the media volume is turned up?

**Comment by Sesu8642** [comment]
Thanks for confirming. I suspect the Android Alarm Manager dependency I use is not compatible with Android 12 and needs to be upgraded. I will try to look into it soon.

**Comment by Sesu8642** [comment]
I was able to reproduce the issue in an emulator and updating dependencies fixed it. The fix will be included in the next release. Please feel free to re-open if the alarm still doesn't work for you after updating.

**Comment by Sesu8642** [comment]
@geronime you mentioned that the alarm could/should be configurable. Do you have use-case where the media volume is unmuted but the alarm could be unwanted?

**Comment by geronime** [comment]
Not really, just some alarm is good enough - I was under the impression that there is simply none implemented.

**Comment by geronime** [comment]
I can confirm that v1.1.1 now has acoustic bell on Android v12.
