### ISSUE TITLE
[Improvement] UI/UX features

### ISSUE THREAD

**Issue by geronime** [Sesu8642/InfusionTimer#4]
1. On the tea detail page, tapping the tea bubble with the countdown would start/pause the timer
2. Tapping the tea bubble once the timer of the previous infusion already finished would fast forward to the next infusion and start the timer (obvious exception: not doing fast forward to the second infusion if I have not done the first one)

**Comment by Sesu8642** [comment]
Having an additional way to control the infusions via the bubble is a good idea. I am thinking about how to tell the user that this is possible in a non-annoying manner...

**Comment by geronime** [comment]
I don't think you need to tell the user. It was actually my first attempt to start the timer. And so was my friend's who thought that he cannot start the timer at all, not realising there is the play button below :-)

**Comment by JaromirDvoracek** [comment]
Yep, that was me. I thought for a while that the countdown doesn't work at all, unfortunately. I have a great skill to overlook tiny buttons :sweat_smile: PS: We're fans of Mei-leaf as well!

**Comment by JaromirDvoracek** [comment]
> Having an additional way to control the infusions via the bubble is a good idea. I am thinking about how to tell the user that this is possible in a non-annoying manner...

![screen1](https://user-images.githubusercontent.com/692744/150339933-148db68c-3504-4cd8-b039-a61fd3b17117.png)

What do you think about a similar approach?

**Comment by geronime** [comment]
I'd add that the "Play" icon would change to "Pause" icon once the timer is started and running; on finishing the infusion the icon changes to "Fast Forward" (this jumps to the next infusion and starts the timer - similar to behaviour on youtube). Scrolling through the infusions would reset the main control icon to "Play".

**Comment by Sesu8642** [comment]
I like that design. Having the infusion information between the buttons makes it very clear what they do. I am a little unsure about the remaining time not being in the center of the bubble. I guess I could hide the button entirely while the timer is running and have the time in the center. But tapping the bubble would still pause.

**Comment by THardi** [comment]
Hallo.
I think: There is no break when pouring tea.  After "Play" I would only offer to cancel and automatically switch to the next counter.  You can always take a step back manually.

**Comment by THardi** [comment]
My other idea:
After the last infusion, the field could appear red in the overview. So you can see immediately that new tee is needed.
![Screenshot_20220126-220634](https://user-images.githubusercontent.com/64699477/151251553-5b75982f-6ebe-4b11-b88a-6c84d9cc903a.jpg)

**Comment by THardi** [comment]
And the next one:
One alarm per tea for remembering to make tea.
Sesu8642:
"Example: Every day at 8am you want an alarm to make your black tea? Did I get this right?"

Its right. Thanks for your mail.

**Comment by Sesu8642** [comment]
@THardi thank you for clarifying. I think you might have a use case that is different from mine and which I don't understand yet.
When I make tea, there are many reasons why I don't want to start the next infusion immediately. For example:
- it takes a couple of seconds to pour the tea
- I want to finish drinking the current infusion before the next one is ready
- I might need to get more water
In your screenshot, it looks like you make 1l of tea per infusion. How can you even drink that much if you start the next infusion immediately after the previous one finished?

It is also unclear to me why you need to track the infusions of multiple teas at the same time and why you need to constantly make new tea. Would you mind to elaborate?

**Comment by Sesu8642** [comment]
@geronime @JaromirDvoracek I (mostly) implemented your suggestions. What do you think about this? @geronime Is this the icon that you meant? It is the one I see on YouTube videos.
![timer_ui_changed](https://user-images.githubusercontent.com/45859254/151442439-946274ad-5548-4153-a7de-4c19126187c3.gif)

**Comment by geronime** [comment]
Perfect!

**Comment by JaromirDvoracek** [comment]
> @geronime @JaromirDvoracek I (mostly) implemented your suggestions. What do you think about this? @geronime Is this the icon that you meant? It is the one I see on YouTube videos. 

Nice! The icon back should be probably compatible with the icon next to the Infusion text :)

**Comment by THardi** [comment]
@Sesu8642
> I think you might have a use case that is different from mine and which I don't understand yet. When I make tea, there are many reasons why I don't want to start the next infusion immediately. For example:
> 
> * it takes a couple of seconds to pour the tea
> * I want to finish drinking the current infusion before the next one is ready
> * I might need to get more water
>   In your screenshot, it looks like you make 1l of tea per infusion. How can you even drink that much if you start the next infusion immediately after the previous one finished?
> 
> It is also unclear to me why you need to track the infusions of multiple teas at the same time and why you need to constantly make new tea. Would you mind to elaborate?

I usually make an infusion of 1 liter of tea in a thermos bottle every evening for the next working day.  That way it won't be as hot the next day.  Unfortunately, I don't always remember how many infusions I've already had.  Deviating from that, I also make a pot from time to time.

**Comment by Sesu8642** [comment]
@THardi 
Now I understand. I added a comment to #5 about remembering the current infusion.

About the daily alarm: I think that it is out of scope for this app. This can probably solved using a repeating entry in a calendar app.
