### ISSUE TITLE
Counting is much faster on GrapheneOS

### ISSUE THREAD

**Issue by JaromirDvoracek** [Sesu8642/InfusionTimer#6]
Hello, thanks for a promising app! I installed it on my [GrapheneOS](https://grapheneos.org/) (Android alternative ROM focused on security and privacy) through f-droid. Android version is 12.

App's second is much faster than a second IRL. Please check my [video](https://youtu.be/FfPWTleUVag) how it looks like.

Is there any way how I can help you to debug this issue?

Jaromir

**Comment by Sesu8642** [comment]
Thanks for this detailed bug report! The countdown is handled by the [Liquid Progress Indicator](https://pub.dev/packages/liquid_progress_indicator) dependency. I am not sure why this happens on your device. The progress indicator takes a [Ticker Provider](https://api.flutter.dev/flutter/scheduler/TickerProvider-class.html) as a parameter. Maybe this can be used to fix this behaviour. I need to investigate.

**Comment by JaromirDvoracek** [comment]
Ah, no objective reason, really - just my old-school habit of removing spaces in application names. Feel free to remove the hyphen, of course.

**Comment by Sesu8642** [comment]
My usage of the library ticker provider is just like in their example app. This [blog post](https://dash-overflow.net/articles/why_vsync/) also suggests that the ticker provider is used correctly.

**Comment by Sesu8642** [comment]
@JaromirDvoracek I found [this issue](https://github.com/flutter/flutter/issues/60917#issuecomment-654378296) which describes a similar behaviour. Could you please try playing with the options mentioned there?

**Comment by JaromirDvoracek** [comment]
Wow, nice catch! Yep, now it works as it should!
