### ISSUE TITLE
No Notification When Screen Is Turned Off

### ISSUE THREAD

**Issue by Nesaijn** [Sesu8642/InfusionTimer#8]
When starting a timer and locking the screen, no notification will be triggered. Only when the screen is turned on the notification will appear.
To be precise, the screen does not have to be unlocked for the notification to appear but only turned on. But when leaving the screen turned off, no notification will appear.

Operating System: Android 11 (LineageOs 18.1)
Hardware: Xperia XA2
App Version: 1.1.0

**Comment by Sesu8642** [comment]
Thanks for reporting!
When starting the timer, there should be a notification indicating the brewing progress almost immediately. Do you get this at all on your device?

**Comment by Nesaijn** [comment]
Yes, it is preeent. Also when the screen is locked but on.

**Comment by Sesu8642** [comment]
But after you turn the screen off and on again, the notification is gone? And do you get the bell sound when the timer finishes?

**Comment by Nesaijn** [comment]
No, after truning the screen off and then on again, the notification is still present. When my screen is on and the timer finishes, I do get the bell sound. But when the screen is off and the timer finishes, I do not get the bell sound.

**Comment by Sesu8642** [comment]
Thanks for your clarifications. I understand the problem now.
Coincidentally, I am also testing on a LOS 18.1 device and I cannot reproduce the issue. However, I noticed that there is quite a long delay between the timer finishing and the bell sound for small timer durations when the screen is off. I will try to investigate some more.

**Comment by Sesu8642** [comment]
I was able to fix the delay and I think the fix will probably fix your issue as well. It will be included in the next release. Please re-open this if your problem persists after upgrading.

**Comment by Nesaijn** [comment]
The latest update fixed the issue for me.
Thank you very much!
